### PR TITLE
Add a continuous curve for the drift derivative calculation

### PR DESCRIPTION
**Pull request by gkaracha**
Continuation of #281, and the last part of addressing #261.

Remaining TODOs:
- [x] Turn `src/continuousDriftDerivative.ml` into a jinja template.
- [x] Add (and comment out) the default configuration for continuous curves in `checker.yaml`.
- [ ] Find a way to keep the tests around (1adefcdb7eed1027334253255ada490b0213b7e7).

### CODE REVIEW

**Comment by gkaracha** [comment]
Not sure how to keep the tests for the continuous curve (1adefcd) around, but I opened #284 since this seems to be a more general issue we have to address while making progress towards addressing #171.

**Comment by gkaracha** [comment]
The continuous curve does not seem to break the e2e tests (see here: https://github.com/tezos-checker/checker/pull/283/commits/215b71adc430fdfb4a30dbc98b6e7f6c569b34ec) so it looks like it is a viable replacement for our current curve, yay!

**Review by dorranh — APPROVED** [review]
LGTM! I'm happy landing this and addressing the question of testing separately since it is a bit of a broader dilemma.

**Comment by gkaracha** [comment]
> LGTM! I'm happy landing this and addressing the question of testing separately since it is a bit of a broader dilemma.

Great, thanks! When we find a way to address #284 in general, I'll happily cherry-pick 1adefcd :smile:

**Pull request merged**
