### PR TITLE
Test both collateral configurations on CI

### PR DESCRIPTION
**Pull request by gkaracha**
Prerequisite for #213.

### CODE REVIEW

**Comment by gkaracha** [comment]
This seems to be breaking the message bot; reverting back to a draft until we resolve this.

**Comment by gkaracha** [comment]
Undrafting; the bot seems to be working after all. I guess writing the output twice is problematic in general though :thinking: (and perhaps a little flaky; statistics can be different for different configurations)

**Comment by dorranh** [comment]
Ah now that is an unforeseen consequence - perhaps we should start plotting histograms instead :sweat_smile:

**Comment by dorranh** [comment]
In all seriousness, I think that with the current approach we are actually overwriting the coverage, gas cost, etc. artifacts. We might want to split them out per workflow (e.g. with a different suffix) and update the comment bot accordingly.

**Comment by gkaracha** [comment]
Yeah, true. My initial thought was to only allow writing gas costs if `${{ matrix.configuration_file }} == "checker-tez.yaml"` but I agree with you. It would be nice to be able to catch regressions for either deployment. Let me turn this again into a draft until this is implemented correctly.

**Comment by dorranh** [comment]
> My initial thought was to only allow writing gas costs if ${{ matrix.configuration_file }} == "checker-tez.yaml"

You know, this might actually be a nicer immediate solution. That way we can go ahead and start testing both and then add support for metrics for FA2 checker in a separate PR.

**Comment by gkaracha** [comment]
> > My initial thought was to only allow writing gas costs if ${{ matrix.configuration_file }} == "checker-tez.yaml"
> 
> You know, this might actually be a nicer immediate solution. That way we can go ahead and start testing both and then add support for metrics for FA2 checker in a separate PR.

More incrementally, eh? :thinking: That sounds good to me; at least we can already safely know that both collateral configurations work, even we don't get extra gas info about the FA2 one (gas costs can still not go overboard though, because if that happens I expect the corresponding e2e test would fail, so that's another safety net). Let's see how adc6c48 does

**Comment by gkaracha** [comment]
I'll go ahead and merge this one so that both collateral configurations are always tested and we can always add support for metrics for collateral=FA2 checker in a separate PR; currently the artifacts stored only capture gas costs etc. for collateral=TEZ.

**Pull request merged**
